[2022-10-26 01:57:26,229][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x28d972b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
[2022-10-26 01:57:26,252][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1710c64a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
[2022-10-26 01:57:26,259][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1710c7070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
