2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Configure stats pid to 26746
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/.config/wandb/settings
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/settings
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_init.py:_log_setup():461] Logging user logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_143930-3spmtcvl/logs/debug.log
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_init.py:_log_setup():462] Logging internal logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_143930-3spmtcvl/logs/debug-internal.log
2022-09-20 14:39:30,966 INFO    MainThread:26746 [wandb_init.py:init():495] calling init triggers
2022-09-20 14:39:30,967 INFO    MainThread:26746 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-09-20 14:39:30,967 INFO    MainThread:26746 [wandb_init.py:init():548] starting backend
2022-09-20 14:39:30,967 INFO    MainThread:26746 [wandb_init.py:init():552] setting up manager
2022-09-20 14:39:30,970 INFO    MainThread:26746 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-09-20 14:39:30,973 INFO    MainThread:26746 [wandb_init.py:init():558] backend started and connected
2022-09-20 14:39:30,973 WARNING MsgRouterThr:26746 [router.py:message_loop():76] message_loop has been closed
2022-09-20 14:39:30,986 INFO    MainThread:26746 [wandb_run.py:_label_probe_notebook():1105] probe notebook
2022-09-20 14:39:30,986 INFO    MainThread:26746 [wandb_init.py:init():636] updated telemetry
2022-09-20 14:39:30,993 ERROR   MainThread:26746 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 647, in init
    backend.interface.publish_header()
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 93, in publish_header
    self._publish_header(header)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 265, in _publish_header
    self._publish(rec)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Configure stats pid to 26746
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/.config/wandb/settings
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/settings
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_init.py:_log_setup():461] Logging user logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_150253-dysc4cu4/logs/debug.log
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_init.py:_log_setup():462] Logging internal logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_150253-dysc4cu4/logs/debug-internal.log
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_init.py:init():495] calling init triggers
2022-09-20 15:02:53,745 INFO    MainThread:26746 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-09-20 15:02:53,746 INFO    MainThread:26746 [wandb_init.py:init():548] starting backend
2022-09-20 15:02:53,746 INFO    MainThread:26746 [wandb_init.py:init():552] setting up manager
2022-09-20 15:02:53,763 ERROR   MainThread:26746 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 553, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 161, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 140, in send
    self.send_server_request(server_req)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
2022-09-20 15:35:34,565 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Configure stats pid to 26746
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/.config/wandb/settings
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/settings
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:_log_setup():461] Logging user logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_153534-3pxmjsff/logs/debug.log
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:_log_setup():462] Logging internal logs to /Users/elvis/Desktop/School/2022/cpsc_536/hw1/wandb/run-20220920_153534-3pxmjsff/logs/debug-internal.log
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:init():495] calling init triggers
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:init():548] starting backend
2022-09-20 15:35:34,566 INFO    MainThread:26746 [wandb_init.py:init():552] setting up manager
2022-09-20 15:35:34,580 ERROR   MainThread:26746 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 553, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 161, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 140, in send
    self.send_server_request(server_req)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/elvis/opt/anaconda3/envs/cpsc/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
