2022-10-26 01:56:06,736 INFO    StreamThr :14558 [internal.py:wandb_internal():88] W&B internal server running at pid: 14558, started at: 2022-10-26 01:56:06.734647
2022-10-26 01:56:06,744 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: status
2022-10-26 01:56:06,745 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: status
2022-10-26 01:56:06,750 INFO    WriterThread:14558 [datastore.py:open_for_write():75] open: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/run-17i2ph6n.wandb
2022-10-26 01:56:06,750 DEBUG   SenderThread:14558 [sender.py:send():303] send: header
2022-10-26 01:56:06,751 DEBUG   SenderThread:14558 [sender.py:send():303] send: run
2022-10-26 01:56:07,029 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: check_version
2022-10-26 01:56:07,032 INFO    SenderThread:14558 [dir_watcher.py:__init__():216] watching files in: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files
2022-10-26 01:56:07,032 INFO    SenderThread:14558 [sender.py:_start_run_threads():928] run started: 17i2ph6n with start time 1666774566.718062
2022-10-26 01:56:07,032 DEBUG   SenderThread:14558 [sender.py:send():303] send: summary
2022-10-26 01:56:07,033 INFO    SenderThread:14558 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-10-26 01:56:07,033 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: check_version
2022-10-26 01:56:07,112 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: run_start
2022-10-26 01:56:07,114 DEBUG   HandlerThread:14558 [meta.py:__init__():34] meta init
2022-10-26 01:56:07,114 DEBUG   HandlerThread:14558 [meta.py:__init__():49] meta init done
2022-10-26 01:56:07,114 DEBUG   HandlerThread:14558 [meta.py:probe():215] probe
2022-10-26 01:56:07,125 DEBUG   HandlerThread:14558 [meta.py:_setup_git():205] setup git
2022-10-26 01:56:07,148 DEBUG   HandlerThread:14558 [meta.py:_setup_git():212] setup git done
2022-10-26 01:56:07,149 DEBUG   HandlerThread:14558 [meta.py:_save_pip():53] save pip
2022-10-26 01:56:07,149 DEBUG   HandlerThread:14558 [meta.py:_save_pip():67] save pip done
2022-10-26 01:56:07,149 DEBUG   HandlerThread:14558 [meta.py:probe():253] probe done
2022-10-26 01:56:07,155 DEBUG   SenderThread:14558 [sender.py:send():303] send: files
2022-10-26 01:56:07,155 INFO    SenderThread:14558 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-10-26 01:56:07,162 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:56:07,162 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:56:07,265 DEBUG   SenderThread:14558 [sender.py:send():303] send: telemetry
2022-10-26 01:56:07,573 INFO    Thread-23 :14558 [upload_job.py:push():143] Uploaded file /var/folders/8n/816m6fhn3tj54_s_p9r0t3hw0000gn/T/tmpubl0djz2wandb/2o2yhmtj-wandb-metadata.json
2022-10-26 01:56:07,786 DEBUG   SenderThread:14558 [sender.py:send():303] send: telemetry
2022-10-26 01:56:08,041 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/requirements.txt
2022-10-26 01:56:08,041 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/wandb-summary.json
2022-10-26 01:56:08,041 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:08,041 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/wandb-metadata.json
2022-10-26 01:56:10,045 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:12,048 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:14,056 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:16,063 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:18,072 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:20,079 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:22,090 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:22,278 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:56:22,278 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:56:24,099 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:26,110 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:28,120 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:30,128 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:56:37,400 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:56:37,401 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:56:38,165 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/config.yaml
2022-10-26 01:56:47,421 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 01:56:52,519 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:56:52,519 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:57:07,627 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:57:07,628 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:57:22,752 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:57:22,752 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:57:33,970 ERROR   SenderThread:14558 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10fa596c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fa596c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fa596c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-10-26 01:57:42,758 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:57:47,398 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 01:57:47,400 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:57:48,502 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:57:50,510 INFO    Thread-19 :14558 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/elvis/Desktop/School/2022/cpsc_536/CPSC532W_hw4/wandb/run-20221026_015606-17i2ph6n/files/output.log
2022-10-26 01:58:02,569 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:58:02,571 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:58:05,362 WARNING FileStreamThread:14558 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x10f097f70>>, args: ('https://api.wandb.ai/files/elvis_cai/HW4IS/17i2ph6n/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 16.6, "system.gpu.0.memoryAllocated": 8.57, "system.gpu.0.temp": 42.29, "system.gpu.0.powerWatts": 4.75, "system.gpu.0.powerPercent": 28.76, "system.cpu": 28.73, "system.memory": 82.8, "system.disk": 34.0, "system.proc.memory.availableMB": 2819.96, "system.proc.memory.rssMB": 216.69, "system.proc.memory.percent": 1.32, "system.proc.cpu.threads": 15.8, "system.network.sent": 3519488, "system.network.recv": 20758528, "_wandb": true, "_timestamp": 1666774648.93289, "_runtime": 82.214828}']}}, 'dropped': 0}}
2022-10-26 01:58:10,616 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 01:58:17,729 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:58:17,732 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:58:32,883 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:58:32,885 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:58:48,030 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:58:48,033 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:58:52,572 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 01:59:03,176 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:59:03,178 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:59:18,301 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:59:18,304 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:59:33,459 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:59:33,461 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 01:59:34,553 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 01:59:48,613 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 01:59:48,614 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 02:00:03,769 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 02:00:03,770 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 02:00:16,518 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 02:00:19,720 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 02:00:19,720 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 02:00:34,896 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 02:00:34,898 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 02:00:50,070 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 02:00:50,072 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
2022-10-26 02:00:58,711 DEBUG   SenderThread:14558 [sender.py:send():303] send: stats
2022-10-26 02:01:05,248 DEBUG   HandlerThread:14558 [handler.py:handle_request():138] handle_request: stop_status
2022-10-26 02:01:05,249 DEBUG   SenderThread:14558 [sender.py:send_request():317] send_request: stop_status
